### ISSUE TITLE
--saveCompiledTests doesn't save different versions for strict/non-strict

### ISSUE THREAD

**Issue by dilijev** [bterlson/test262-harness#105]
This can block finding an issue which repros under only one. (It's a gotcha that, once known, is easier to work with but a gotcha nonetheless.)

/cc @jackhorton

**Comment by rwaldron** [comment]
I hit this yesterday, easily remedied by extending the file naming to: 

```js   
file.js.<hostType>.<scenario>.<pass|fail>
```  

`scenario` will be either `default` or `strict`. 

I'd like to hold off until @jugglinmike has completed the migration to test262-stream
