### ISSUE TITLE
Confusion with AsyncTestFailure token

### ISSUE THREAD

**Issue by Ms2ger** [bterlson/test262-harness#119]
https://github.com/tc39/test262/blob/a83bae960c801e752158461021d9e8943ec152ce/INTERPRETING.md#flags talks about the string `Test262:AsyncTestFailure:` with a trailing colon; since commit 6d512ec4c0a14753a38677580c50abe5e66bf4c7, this repo looks for `Test262:AsyncTestFailure ` with a trailing *space*.

**Comment by rwaldron** [comment]
This has been fixed since https://github.com/bterlson/test262-harness/commit/97d79342239552f5a445c77eb0c4a62abaec5558
