### ISSUE TITLE
prelude broken

### ISSUE THREAD

**Issue by astlaurent1** [bterlson/test262-harness#124]
## Symptom

While using `--prelude`, I consistently see the following error.
```
Expected no error, got SyntaxError: Invalid regular expression: missing /
```

## Suspected Cause
If you log out the test contents, you'll find that it inserts `/[HERE]/ Copyright` rather than `[HERE]// Copyright`. This creates a line starting with `/ Copyright`, which is an unclosed regex. Hence the SyntaxError

## Possible Solution
I was able to work around this by modifying `insertPrelude` (https://github.com/bterlson/test262-harness/blob/master/bin/run.js#L194) to slice up to `index - 1` rather than `index`:

```js
function insertPrelude(test) {
  const index = test.insertionIndex;
  if (index === -1) {
    return test;
  }

  if (preludeContents) {
    test.contents = test.contents.slice(0, index - 1) + // change here
      preludeContents +
      test.contents.slice(index - 1); // change here
  }

  return test;
}
```

## Notes
I suspect this is related to the recent change in test262-stream: https://github.com/bocoup/test262-stream/releases

I am willing to submit a PR, but I don't know if it should be here, or if there is a problem with test262-stream, or if the problem lies elsewhere

**Comment by rwaldron** [comment]
Thanks for the report! I will take a look at test262-stream and figure out which project needs to be fixed or updated.

**Comment by rwaldron** [comment]
I've tracked the issue to changes that were necessary as a result of implementing hashbang support in Test262-Stream. There is an open PR with a fix and tests here: https://github.com/bocoup/test262-stream/pull/23

The issue wasn't detected by Test262-Harness's tests because none of the collateral fixtures had copyright headers in them. To address that, I've created collateral fixtures that include copyright headers.

**Comment by astlaurent1** [comment]
That looks great! Thanks for addressing this so quickly :)

**Comment by astlaurent1** [comment]
test262-stream@1.2.2 fixes this issue - thanks again!

**Comment by rwaldron** [comment]
Published: 

```
test262-harness@5.1.1
```
