### ISSUE TITLE
Indicate test failure via exit code

### ISSUE THREAD

**Issue by alangpierce** [bterlson/test262-harness#131]
Thanks for the project!

I'd like to integrate this into CI for my project ([Sucrase](https://github.com/alangpierce/sucrase)) and noticed that under normal CLI usage, it exits 0 even if some tests failed. Normally I'd expect a test runner to exit nonzero if it successfully ran tests and determined that some tests failed, maybe using different exit codes to distinguish between "failed to run tests" and "some tests failed". Could the test runner be changed to exit nonzero in that case, maybe behind an option?

The best workaround that I can see is to use the JSON reporter and check for at least one test with `!test.result.pass`, but it would be nice to use the regular reporter so I get user-friendly continuous output.

**Comment by leobalter** [comment]
For the reality on usage of test262-harness, I'd prefer to keep it as it is.

It's usual that most browser engines will not pass all tests and I take advantage of the output reported with failures and passings.

An actual non 0 exit indicates me not a test failure but a failure in running the tests which is pretty informative.

My suggestion is - for automated processes - to use the json output and filter the result contents.

**Comment by alangpierce** [comment]
Fair enough. For my use case, my strategy is to narrow it down to a list of tests that pass, fix or skip the others (using a preprocessor or custom CLI invocation), and then include the good tests in each PR build to confirm that there aren't any regressions, so "test failures" and "error running tests" are both things that would need fixing. But I can see how it would be more common to want a report of which tests passed and failed, given that the full list never all passes in practice. And processing the json output isn't so hard for me since I already am writing a wrapper script.
