### ISSUE TITLE
annexB/B.2.1.js fails in test262-harness with -r node, >= 0.11

### ISSUE THREAD

**Issue by smikes** [bterlson/test262-harness#34]
Here's the failure on >= 0.11.  It only happens with -r node, -r node-ip

Again, `test262` and `test262-harness` are siblings:

`for x in 0.10 0.11 0.12 1.0 1.1 1.2 ; do nvm use $x; ../test262-harness/bin/run.js test/annexB/B.2.1.js -r node-ip ; done`

Output is:
```
Now using node v0.10.35
Ran 1 tests
1 passed
0 failed
Took 0.027 seconds
Now using node v0.11.15
FAIL test/annexB/B.2.1.js
     Object.getOwnPropertyDescriptor returns data desc for functions on built-ins (Global.escape)
     Exp: no error
     Got: Error: not enumerable

Ran 1 tests
0 passed
1 failed
Took 0.044 seconds
Now using node v0.12.0
FAIL test/annexB/B.2.1.js
     Object.getOwnPropertyDescriptor returns data desc for functions on built-ins (Global.escape)
     Exp: no error
     Got: Error: not enumerable

Ran 1 tests
0 passed
1 failed
Took 0.044 seconds
Now using io.js v1.0.4
FAIL test/annexB/B.2.1.js
     Object.getOwnPropertyDescriptor returns data desc for functions on built-ins (Global.escape)
     Exp: no error
     Got: Error: not enumerable

Ran 1 tests
0 passed
1 failed
Took 0.046 seconds
Now using io.js v1.1.0
FAIL test/annexB/B.2.1.js
     Object.getOwnPropertyDescriptor returns data desc for functions on built-ins (Global.escape)
     Exp: no error
     Got: Error: not enumerable

Ran 1 tests
0 passed
1 failed
Took 0.046 seconds
Now using io.js v1.2.0
FAIL test/annexB/B.2.1.js
     Object.getOwnPropertyDescriptor returns data desc for functions on built-ins (Global.escape)
     Exp: no error
     Got: Error: not enumerable

Ran 1 tests
0 passed
1 failed
Took 0.047 seconds
```

I suspect the problem is that when the global object is set up inside `test262-harness` code, the `enumerable: false` descriptor property is not preserved.

**Comment by smikes** [comment]
Some context around the API changes: <http://strongloop.com/strongblog/node-js-v0-12-apis-breaking/#vm_vm_runinnewcontext_code_sandbox_options>

> vm.runInThisContext() compiles code, runs it and returns the result. Running code does not have access to local scope, but does have access to the current global object.

vs

>  vm.runInNewContext compiles code, contextifies sandbox if passed or creates a new contextified sandbox if it’s omitted, and then runs the code with the sandbox as the global object and returns the result.

see also <https://github.com/iojs/io.js/issues/864>

**Comment by bterlson** [comment]
Node v.0.12 will continue to not work properly. This is ok because it's fixed in later versions.
