### ISSUE TITLE
Last error is reported, not first; and test continues despite first error

### ISSUE THREAD

**Issue by smikes** [bterlson/test262-harness#36]
Test:
```
// Copyright 2015 Cubane Canada, Inc.  All rights reserved.
// See LICENSE for details.

/*---
info: >
 test harness reports last error
author: Sam Mikes
description: Expected message 1
---*/

assert(false, "message 1");
assert(false, "message 2");
```

```
FAIL test/built-ins/Symbol/species/Symbol.species.in_Promise.js
     RegExp[Symbol.species] exists per spec
     Exp: no error
     Got: Error: message 2
```

I'd expect a `message 1` and for the test to be stopped at that point.  This may be irrelevant when we're using VMs, but a test may contain a guard where an early failure prevents later, less legible failures.

**Comment by juandopazo** [comment]
Many test runners continue running after a failure, but most of them provide the option to stop at the first one.

**Comment by bterlson** [comment]
I am going to throw on the first error (basically $ERROR will throw an exception). Reason being that I need to report the line number where the error occurred as many new test262 tests don't have informative assertion messages.

**Comment by smikes** [comment]
:-|

**Comment by bterlson** [comment]
Now reporting first error.
