### ISSUE TITLE
use ch.exe flags on jsshell command

### ISSUE THREAD

**Issue by leobalter** [bterlson/test262-harness#49]
I finally started using test262-harness w/ ChakraCore - I can't say why I've never tried it before.

It's working nice and fast, but I want an extra thing: use Chakra flags on the jsshell command.

This works nice:

```
$ test262-harness -r jsshell -e "ch.exe" test/built-ins/TypedArray/prototype
``` 

The following doesn't:

```
$ test262-harness -r jsshell -e "ch.exe ES6All" test/built-ins/TypedArray/prototype
``` 

My Windows env is super noob, using git-bash enough to get me running ChakraCore. There's probably a better way to run the tests with Chakra, but I'm a bit lost.

**Comment by bterlson** [comment]
`test262-harness -r jsshell -e "ch.exe /ES6All" test/built-ins/TypedArray/prototype` should work (note the slash prior to ES6All). You can also pass args separately using the --consoleArguments option (helpful mostly when using a config file and you just want to override the arguments and not the executable path).

**Comment by leobalter** [comment]
nice! thank you!

**Comment by bterlson** [comment]
btw I'm surprised `-r jsshell` just works. I have a runner built for chakra that I haven't committed but I can give it to you if you're interested.

**Comment by leobalter** [comment]
Yes, please!
