### ISSUE TITLE
Can't execute all test262 on Node

### ISSUE THREAD

**Issue by thorn0** [bterlson/test262-harness#50]
Node 6.1, Windows 7 x64
```
> git clone https://github.com/tc39/test262.git --depth 1
> npm i test262-harness
> node_modules\.bin\test262-harness -T test262
```
It never executes all of the tests. Sometimes it ends up like following:
```
PASS prop-desc.jsD:\dev\test262-1\node_modules\highland\lib\index.js:577
            throw new Error('Cannot write to stream after nil');
            ^

Error: Cannot write to stream after nil
    at D:\dev\test262-1\node_modules\highland\lib\index.js:577:19
    at D:\dev\test262-1\node_modules\test262-harness\bin\run.js:125:21
    at Runner._testDone (d:\dev\test262-1\node_modules\test262-harness\lib\runner.js:243:9)
    at d:\dev\test262-1\node_modules\test262-harness\lib\runners\node.js:37:28
    at d:\dev\test262-1\node_modules\highland\lib\index.js:1607:13
    at Stream.s._send (d:\dev\test262-1\node_modules\highland\lib\index.js:1332:9)
    at Stream.write (d:\dev\test262-1\node_modules\highland\lib\index.js:1422:18)
    at Stream._send (d:\dev\test262-1\node_modules\highland\lib\index.js:808:26)
    at Stream.write (d:\dev\test262-1\node_modules\highland\lib\index.js:1422:18)
    at d:\dev\test262-1\node_modules\highland\lib\index.js:584:15
```
Sometimes it just stops without any messages or summary.

However, it works for subsets of the tests like
```
> node_modules\.bin\test262-harness -T test262 annexB\**\*.js
```

**Comment by avdg** [comment]
I wonder if this is still an issue.

**Comment by avdg** [comment]
I did a run and found no crashes on test262-harness level. Although this is thanks to recent fixes like bterlson/eshost#9 and tc39/test262#750

**Comment by thorn0** [comment]
I've started it 2 hours ago, and it's still running. :)

**Comment by avdg** [comment]
I've use -t 4

**Comment by avdg** [comment]
And it's a good indication if it's still running ;-)

**Comment by thorn0** [comment]
```
Ran 45086 tests
40683 passed
4403 failed
```
I'm closing the issue.

**Comment by avdg** [comment]
Hmmm node v6.5.0 only has 2554 failed. I wonder if that is from using v6.4.x?

**Comment by thorn0** [comment]
On v6.5.0:
```
Ran 45086 tests
42520 passed
2566 failed
```

**Comment by bterlson** [comment]
Thanks for the updates guys!

I hear you on perf - I'm working to address it. If you're curious, the answer is batch mode so we don't spin up a node process per test but instead one process per N tests (where N is approximately 75).

**Comment by avdg** [comment]
Compared to the python runner, this is already running way faster (they don't have multithread support except for a very short time). But further improvements are welcome given the large number of tests that are being executed (and the speedups in feedback loops to improve js engines).

Later I may look into options to make it work with pre-compilers (code-to-code converters). I'm currently not happy with the arguments passing option. But meh, any progress is good and I'm too busy to fix that specific issue for now (I should cut this excuse at some point though).
