### ISSUE TITLE
Update eshost

### ISSUE THREAD

**Issue by avdg** [bterlson/test262-harness#66]
Can eshost be updated to the latest version? I've seen that the warning got removed on the latest version but npm doesn't use that version yet.

Thanks!

**Comment by avdg** [comment]
The error involved fs.unlink

**Comment by bterlson** [comment]
Hmm, it was a minor update to eshost, so you should get it if you just npm update your test262-harness?

**Comment by avdg** [comment]
It doesn't update to 3.3.x with version set to ^3.2.0

See https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by bterlson** [comment]
Oh sorry, I didn't realize the harness was 3.2.0 not 3.3.0. Will fix!

**Comment by bterlson** [comment]
@avdg With current package.json I am getting 3.3.x, docs confirm ^3.2.0 is >= 3.2.0 and < 4.0.0. If I understand correctly.

**Comment by avdg** [comment]
Yes I can confirm I'm getting this version
