### ISSUE TITLE
Should auto-update lib/helpers/ (?) or allow setting new path for lib/helpers

### ISSUE THREAD

**Issue by smikes** [bterlson/test262-harness#7]
Using this for development; I notice that if I change `test/harness/propertyHelper.js` I then have to make sure to manually install the helper into `test262-harness/lib/helpers`.

Either the harness should auto-update the helpers directory, or it should be possible to tell the harness directory to use a different helpers directory.

**Comment by rwaldron** [comment]
I don't think this is relevant anymore
